// Informations
export const GET_INFORMATIONS = 'GET_INFORMATIONS';
export const ADD_INFORMATION = 'ADD_INFORMATION';
export const DELETE_INFORMATION = 'DELETE_INFORMATION';
export const INFORMATION_LOADING = 'INFORMATION_LOADING';

//Authentication and register
export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

//Getting all users
export const ALL_USERS_LOADING = "ALL_USERS_LOADING";
export const ALL_USERS_LOADED = "ALL_USERS_LOADED";
export const USER_DELETE = "USER_DELETE";

//Adding/Removing Admin
export const ADD_ADMIN = "ADD_ADMIN";
export const REMOVE_ADMIN = "REMOVE_ADMIN";

//Changing roles
export const CHANGE_ROLE = "CHANGE_ROLE";

//ReservationHours
export const ADD_RESERVATION_HOURS = "ADD_RESERVATION_HOURS";
export const GET_RESERVATION_HOURS = "GET_RESERVATION_HOURS";
export const GET_MY_RESERVATION_HOURS = "GET_RESERVATION_HOURS";
export const DELETE_RESERVATION_HOURS = "DELETE_RESERVATION_HOURS";
export const RESERVATION_HOURS_LOADING = "RESERVATION_HOURS_LOADING";