export const GET_INFORMATIONS = 'GET_INFORMATIONS';
export const ADD_INFORMATION = 'ADD_INFORMATION';
export const DELETE_INFORMATION = 'DELETE_INFORMATION';
export const INFORMATION_LOADING = 'INFORMATION_LOADING';